spring:
  application:
    name: msa-eureka-server
server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
